name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest 

    steps:
      - name: debug
        uses: mxschmitt/action-tmate@v3

    # # Install dependencies
    # - name: Install .NET Core
    #   run: |
    #     echo ${{ github.workspace }}
    #     echo $GITHUB_WORKSPACE
    #     echo $pwd
